### ISSUE TITLE
What chips are used?

### ISSUE THREAD

**Issue by angrypig555** [c0pperdragon/SingleBreadboardComputer#2]
I could not find any list of what chips are used. Is there any?

**Comment by c0pperdragon** [comment]
Most of the ICs are in the schematic with their part numbers:
https://github.com/c0pperdragon/SingleBreadboardComputer/blob/main/mainboard/mainboard.pdf
I only forgot to label the CPU, which is a W65C02S.  The oscillator is some generic part.

**Comment by angrypig555** [comment]
Okay thanks. Ill find a generic oscillator then.
